--- #YAML:1.0
name:               MyCPAN-App-DPAN
version:            1.28
abstract:           Create a custom, private DarkPAN repository that looks just like a real CPAN
author:
    - brian d foy <bdfoy@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CPAN::Checksums:      0
    CPAN::PackageDetails:  0.24
    Log::Log4perl:        0
    MyCPAN::Indexer:      1.28
    Test::Output:         0.13
    version:              0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
